baseURL = "http://example.org/"
languageCode = "en-us"
title = "Muts Meer"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Jackie Sanchez - All rights reserved"
#disqusShortname = "mutsmeer"
googleAnalytics = "UA-119902709-2" 

[params]
  logo = "/images/top.bmp"
  description ="Gallery"
  customCss = ["custom.css"]
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Jackie Sanchez"
  thumbnail = "/images/author.bmp"
  description = "Creator of this blog."

[params.index]
  picture = "/images/home.jpg"
  title = "Muts Meer"
  #ssubtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''Years of traditional Colombian hand craft have arrived to the Netherlands. A colorful way to connect with your child and to express your beauty. Authentically hand made turbants (headbands) in different size, style and material. Please go the the gallery to see some options and let me now if I can make one for you. Mail me at mutsmeer@gmail.com or look at my instagram.'''
  alertbar = true

[params.social]
  instagram = "mutsmeer"

## Main Menu
[[menu.main]]
    name = "Gallery"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
